name: Build and deploy to server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup git-yt-dlp
        uses: actions/checkout@v4
        with:
          repository: edvordo/yt-dlp
          path: git-yt-dlp

      - name: setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: setup python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: do-the-thing
        env:
          TWITCH_CHANNEL_NAME: ${{ secrets.TWITCH_CHANNEL_NAME }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_SECRET: ${{ secrets.TWITCH_SECRET }}

          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          YOUTUBE_CATEGORY_ID: $YOUTUBE_CATEGORY_ID
          YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}

          MAIL_PROTOCOL: ${{ secrets.MAIL_PROTOCOL }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: |
          cat /etc/os-release
          php -v
          python3 --version
          ffmpeg -version
          composer install
          php test.php



